add lessons 10 tasks (WIP)
Alwayswannasad/python_courses pull request #3
Opened 2020-11-26 16:41 UTC by Alwayswannasad

2020-12-02 16:22 UTC, podhornyi requested changes

2020-12-02 16:22 UTC, podhornyi commented on lesson_10.py
> +    def _set_index(self, index, sign=''):
Приватные метода по соглашению должны быть в самом низу класса

2020-12-02 16:22 UTC, podhornyi commented on lesson_10.py
> +    def turn_channel(self, num):
Создай несколько `TVController`, и после переключения канала на одном из них - канал поменяется на всех остальных.
А все потому что ты меняешь `TVController.GLOBAL_INDEX` - это переменная класса.
Сделай `self.channel_index = 0  # первый канал из списка` в init методе и дальше меняй self.channel_index.

GLOBAL_INDEX можно вообще удалить

2020-12-04 22:53 UTC, Alwayswannasad commented on lesson_10.py
> +    def _set_index(self, index, sign=''):
done

2020-12-05 11:35 UTC, podhornyi approved these changes

2020-12-17 15:37 UTC, merged