Decorators homework Lesson-14
Alwayswannasad/python_courses pull request #7
Opened 2020-12-05 16:50 UTC by Alwayswannasad

2020-12-05 18:58 UTC, podhornyi requested changes

2020-12-05 18:58 UTC, podhornyi commented on decorators_hw.py
> +            func_string = "".join(f(args[0])).split()
`args[0]` > `*args`

2020-12-05 18:58 UTC, podhornyi commented on decorators_hw.py
> +                return False
should return False and print the reason it failed

2020-12-05 18:58 UTC, podhornyi commented on decorators_hw.py
> +                return False
should return False and print the reason it failed

2020-12-05 18:58 UTC, podhornyi commented on decorators_hw.py
> +                    return False
should return False and print the reason it failed

2020-12-07 10:57 UTC, podhornyi requested changes

2020-12-07 10:57 UTC, podhornyi commented on decorators_hw.py
> +            print()
лишнее

2020-12-07 10:57 UTC, podhornyi commented on decorators_hw.py
> +assert create_slogan(123) is False
`is` сравнивает ID объектов
тут это еще корректно делать, потому что False/True/None - синглтоны и ИД у них всегда один и тот же

`assert not create_slogan(123)` - так правильней будет

2020-12-07 10:57 UTC, podhornyi commented on decorators_hw.py
> +assert create_slogan('Nikita') is False
`assert not create_slogan('Nikita')` - так правильней будет

2020-12-07 12:30 UTC, Alwayswannasad commented on decorators_hw.py
> +            print()
случайно оставил, когда проверял args

2020-12-07 12:30 UTC, Alwayswannasad commented on decorators_hw.py
> +assert create_slogan(123) is False
спасибо, еще про это почитаю

2020-12-07 14:59 UTC, podhornyi approved these changes

2020-12-07 15:34 UTC, merged